CAMERA_INDEX = 0
CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080

MAX_HANDS = 1
DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

GESTURE_HOLD_SECONDS = 1.0

WINDOW_NAME = "AirTouch - Gesture Test"
FULLSCREEN = False

SERIAL_PORT = "COM7"  # change this to match your ESP32's port in Device Manager
SERIAL_BAUD_RATE = 9600